### ISSUE TITLE
Nitpick: `select old item` misbehaviour without selection

### ISSUE THREAD

**Issue by Chr1s70ph** [sentriz/cliphist#36]
Running `cliphist list | dmenu | cliphist decode | wl-copy` without a selection (i.e. pressing ESC to close dmenu) and pasting afterwards leads to a blank paste.   
Since `dmenu` returns nothing, `cliphost decode` can't find anything, and nothing is passed onto wl-copy hence clearing the current clipboard selction. 

To remedy this, I made this tiny helper script. This saves the last output, and in case `dmenu` it reverts back to the most recent clipboard entry.

```bash
#!/bin/bash
# If $NEW is run, and no selection was made
# pasting would result in an empty string
# This helper script eliminates that

PREVIOUS=$( wl-paste )
NEW=$( cliphist list | dmenu | cliphist decode )

echo $NEW

if [ ! -z "$NEW" -a "NEW" != " " ]; then
  echo $NEW | wl-copy
else
  echo $PREVIOUS | wl-copy
fi

```

**Comment by Chr1s70ph** [comment]
This would fit perfectly in `/usr/bin/...` where you could pass dmenu as a command line argument

Not sure if this is out of the scope of this project tho

**Comment by sentriz** [comment]
ah yes this was mentioned before [here](https://github.com/sentriz/cliphist/issues/29#issuecomment-1336499636) resulting in a similar script to yours (PS it looks like `$PREVIOUS | wl-copy` is not needed, since coping the last item vs doing nothing should be the same thing)

maybe it could be added to the [contrib](https://github.com/sentriz/cliphist/tree/master/contrib) folder? :+1:
