### ISSUE TITLE
Feature request: add option to remove numbers from `cliphist list`

### ISSUE THREAD

**Issue by fritzrehde** [sentriz/cliphist#41]
Personally, I don't quite understand the purpose or benefit of seeing the ids next to the copied test. I would just like to see the copied test. Would it be possible to add an option that prints the copied items without the ids? Thanks for the awesome program!

**Comment by sentriz** [comment]
howdy. unfortunately it's not possible, since the numbers are IDs that reference rows in the cliphist database, which hold the input byte for byte 

if you were to take the stdout of your dmenu (eventually piped into wl-copy) literally, you would miss out on newline data, tab characters, images, etc

at least for me these nuances in the text are really important for editing in vim etc

**Comment by shvedes** [comment]
> Personally, I don't quite understand the purpose or benefit of seeing the ids next to the copied test. I would just like to see the copied test. Would it be possible to add an option that prints the copied items without the ids? Thanks for the awesome program!

Hello. This is a small script that cuts the ID before the copied text and outputs the entire list in rofi. I hope it helps you.

```bash
#!/usr/bin/env bash

cliphist_list=$(cliphist list)

cliphist_array=()
while read -r line; do
  cliphist_array+=("${line#*[[:blank:]]}")
done <<< "$cliphist_list"

rofi_options=$(printf "%s\n" "${cliphist_array[@]}")

# Change rofi path to yours
chosen=$(echo -e "${rofi_options}" | rofi -dmenu -i -p "Clipboard:" -theme "$HOME"/.config/rofi/launchers/clipboard/launcher.rasi)

echo "$chosen" | tr -d '\n' | wl-copy


```

**Comment by sentriz** [comment]
@shvedes if you're using the master version of cliphist (where the separator is tab character instead of dot)

then you could try ask rofi to hide it for you

`cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy`

this has the benefit of also working for binary data and stuff with unusual white space

**Comment by fritzrehde** [comment]
What @sentriz said works well, but for me it prints an empty first column, so there is a bunch of unnecessary whitespace on the left. What I prefer is this:
```
cliphist list | cut -f 2- | rofi -dmenu | wl-copy
```
`cut` automatically uses `TAB` as a delimiter, and the `-f 2-` guarantees that it will keep all fields (i.e. fields seperated by tabs) except the first one. This includes an edge case where your copied text contains tabs itself, and then only selecting the second column would not select everything. Hope this helps someone.

**Comment by fritzrehde** [comment]
However, the problem I get with mine is that leading whitespace also gets deleted, because it is counted as part of the first tab.

**Comment by sentriz** [comment]
@fritzrehde that works, but if you skip the "cliphist decode" then all whitespace will be not be preserved. that's why cliphist needs the ID

(also forgot that in my example, updated)

and you're right about rofi printing the extra whitespace seems like a bug in rofi?

`$ printf "1\t%s\n" one two three | rofi -dmenu -display-columns 2`
![image](https://user-images.githubusercontent.com/6832539/231521042-9675b25c-686a-43c5-99ba-4f390c882d07.png)

`$ printf "1\t%s\n" one two three | fzf -d $'\t' --with-nth 2`

https://user-images.githubusercontent.com/6832539/231521130-592285b8-020f-4eec-a155-ad439be76f5c.mp4

**Comment by sentriz** [comment]
added a bug/question to rofi about that here:
https://github.com/davatorium/rofi/issues/1834

**Comment by sentriz** [comment]
now it's it's fixed with the master version of rofi after https://github.com/davatorium/rofi/issues/1834

so you should be able to do `cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy`

and this will make sure all whitespace from your original selection and images etc are preserved since the "decode" command is used

**Comment by sentriz** [comment]
added "faq" section here https://github.com/sentriz/cliphist#faq

**Comment by fritzrehde** [comment]
Cool, that's very helpful. Thanks!

**Comment by sentriz** [comment]
PRs are welcome

**Comment by sentriz** [comment]
it looks like fuzzel doesn't support any options that would help

**Comment by Frestein** [comment]
> Can you add fuzzel command too ?

This works for me.
`cliphist list | awk -F$'\t' '{print $2}' | fuzzel --dmenu | cliphist decode | wl-copy`
