### ISSUE TITLE
Possible to use with xclip ?

### ISSUE THREAD

**Issue by foxjaw** [sentriz/cliphist#76]
On sway cliphists rocks with wl-clipboard.  
On i3 I currently configured greenclip.  

Is this project works only with wl-clipboard / other wl based protocols ? Or can the command be piped properly to support x11/xclip too ?  

### PS
I have tried these so far just for curiosity:  
```
cliphist list | rofi -dmenu | cliphist decode | xclip -selection c -

xclip -selection c $(cliphist list | rofi -dmenu | cliphist decode)
```
dumbly without any luck.

**Comment by sentriz** [comment]
you'd still need to "watch" clipboard changes and pipe them into `cliphist store`

maybe try something like

`while 1; xclip -o -selection c | cliphist store; sleep 1; end`?

**Comment by sentriz** [comment]
I don't have an x11 system sorry

you just need to pipe clipboard changes into cliphist store, and retrieve with list and decode

**Comment by phanen** [comment]
Btw, you can use `clipnotify` to avoid polling in x11, which works well in my case:
```fish
while clipnotify; xclip -o -selection c | cliphist store; end
```

**Comment by phanen** [comment]
Works well for me, and I still use bspwm now ([`.xinitrc`](https://github.com/phanen/.dotfiles/blob/9ecb1bcd66460f4a6a84d1ff79f4e4fde4b77836/.xinitrc?plain=1#L34))

About "polling", I just mean `xclip` will only run on your "copy event"(e.g. press `ctrl-c` on selected text) rather than on each second. It may cost less, and handle some cases in which you want to copy multiple times within 1 second. (:
