### ISSUE TITLE
Implement secret clipboard entry conventions

### ISSUE THREAD

**Issue by 42willow** [sentriz/cliphist#80]
https://github.com/keepassxreboot/keepassxc/issues/10233#issuecomment-1913151267

Code snippet from keepassxc
```cpp
    mime->setData("x-kde-passwordManagerHint", QByteArrayLiteral("secret"));
```

**Comment by 42willow** [comment]
May be related to #58 or may be only an issue with my setup

**Comment by sentriz** [comment]
I think you would need some option for wl-paste --watch to achieve this. something like "if x-kde-xxx is available as a mime option then don't do anything"

this is still a bit of a hack think

@bugaevc has also mentioned ideally we could have Wayland extensions to that keepass could set a "clipboard state" metadata that wl-paste would be able to ignore sensitive stuff. or pass the metadata in to cliphist so that it can ignore it

**Comment by bugaevc** [comment]
Related: https://github.com/bugaevc/wl-clipboard/issues/177

**Comment by sentriz** [comment]
closing re #93
